In [2]:
import numpy as np
import pandas as pd

In [4]:
Dataset=pd.read_csv("CKD.csv")

In [6]:
Dataset

age         bp sg  al  su     rbc        pc         pcc  \
0     2.000000  76.459948  c   3   0  normal  abnormal  notpresent   
1     3.000000  76.459948  c   2   0  normal    normal  notpresent   
2     4.000000  76.459948  a   1   0  normal    normal  notpresent   
3     5.000000  76.459948  d   1   0  normal    normal  notpresent   
4     5.000000  50.000000  c   0   0  normal    normal  notpresent   
..         ...        ... ..  ..  ..     ...       ...         ...   
394  51.492308  70.000000  a   0   0  normal    normal  notpresent   
395  51.492308  70.000000  c   0   2  normal    normal  notpresent   
396  51.492308  70.000000  c   3   0  normal    normal  notpresent   
397  51.492308  90.000000  a   0   0  normal    normal  notpresent   
398  51.492308  80.000000  a   0   0  normal    normal  notpresent   

             ba         bgr  ...        pcv            wc        rc  htn   dm  \
0    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
1    notpresent  148.112676  ...  34.000000  12300.000000  4.705597   no   no   
2    notpresent   99.000000  ...  34.000000   8408.191126  4.705597   no   no   
3    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
4    notpresent  148.112676  ...  36.000000  12400.000000  4.705597   no   no   
..          ...         ...  ...        ...           ...       ...  ...  ...   
394  notpresent  219.000000  ...  37.000000   9800.000000  4.400000   no   no   
395  notpresent  220.000000  ...  27.000000   8408.191126  4.705597  yes  yes   
396  notpresent  110.000000  ...  26.000000   9200.000000  3.400000  yes  yes   
397  notpresent  207.000000  ...  38.868902   8408.191126  4.705597  yes  yes   
398  notpresent  100.000000  ...  53.000000   8500.000000  4.900000   no   no   

     cad  appet    pe  ane classification  
0     no    yes   yes   no            yes  
1     no    yes  poor   no            yes  
2     no    yes  poor   no            yes  
3     no    yes  poor  yes            yes  
4     no    yes  poor   no            yes  
..   ...    ...   ...  ...            ...  
394   no    yes  poor   no            yes  
395   no    yes  poor  yes            yes  
396   no   poor  poor   no            yes  
397   no    yes  poor  yes            yes  
398   no    yes  poor   no             no  

[399 rows x 25 columns]

In [8]:
Dataset=pd.get_dummies(Dataset,dtype=int,drop_first=True)

In [10]:
Dataset

age         bp  al  su         bgr          bu        sc  \
0     2.000000  76.459948   3   0  148.112676   57.482105  3.077356   
1     3.000000  76.459948   2   0  148.112676   22.000000  0.700000   
2     4.000000  76.459948   1   0   99.000000   23.000000  0.600000   
3     5.000000  76.459948   1   0  148.112676   16.000000  0.700000   
4     5.000000  50.000000   0   0  148.112676   25.000000  0.600000   
..         ...        ...  ..  ..         ...         ...       ...   
394  51.492308  70.000000   0   0  219.000000   36.000000  1.300000   
395  51.492308  70.000000   0   2  220.000000   68.000000  2.800000   
396  51.492308  70.000000   3   0  110.000000  115.000000  6.000000   
397  51.492308  90.000000   0   0  207.000000   80.000000  6.800000   
398  51.492308  80.000000   0   0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...          0            0           0   
1    137.528754  4.627244  10.700000  ...          1            0           0   
2    138.000000  4.400000  12.000000  ...          1            0           0   
3    138.000000  3.200000   8.100000  ...          1            0           0   
4    137.528754  4.627244  11.800000  ...          1            0           0   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...          1            0           0   
395  137.528754  4.627244   8.700000  ...          1            0           0   
396  134.000000  2.700000   9.100000  ...          1            0           0   
397  142.000000  5.500000   8.500000  ...          1            0           0   
398  140.000000  5.000000  16.300000  ...          1            0           0   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0          0       0        0          1       1        0                   1  
1          0       0        0          1       0        0                   1  
2          0       0        0          1       0        0                   1  
3          0       0        0          1       0        1                   1  
4          0       0        0          1       0        0                   1  
..       ...     ...      ...        ...     ...      ...                 ...  
394        0       0        0          1       0        0                   1  
395        1       1        0          1       0        1                   1  
396        1       1        0          0       0        0                   1  
397        1       1        0          1       0        1                   1  
398        0       0        0          1       0        0                   0  

[399 rows x 28 columns]

In [12]:
Dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [14]:
# input and output data
independent=Dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [16]:
independent

age         bp  al  su         bgr          bu        sc  \
0     2.000000  76.459948   3   0  148.112676   57.482105  3.077356   
1     3.000000  76.459948   2   0  148.112676   22.000000  0.700000   
2     4.000000  76.459948   1   0   99.000000   23.000000  0.600000   
3     5.000000  76.459948   1   0  148.112676   16.000000  0.700000   
4     5.000000  50.000000   0   0  148.112676   25.000000  0.600000   
..         ...        ...  ..  ..         ...         ...       ...   
394  51.492308  70.000000   0   0  219.000000   36.000000  1.300000   
395  51.492308  70.000000   0   2  220.000000   68.000000  2.800000   
396  51.492308  70.000000   3   0  110.000000  115.000000  6.000000   
397  51.492308  90.000000   0   0  207.000000   80.000000  6.800000   
398  51.492308  80.000000   0   0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  rbc_normal  pc_normal  pcc_present  \
0    137.528754  4.627244  12.518156  ...           1          0            0   
1    137.528754  4.627244  10.700000  ...           1          1            0   
2    138.000000  4.400000  12.000000  ...           1          1            0   
3    138.000000  3.200000   8.100000  ...           1          1            0   
4    137.528754  4.627244  11.800000  ...           1          1            0   
..          ...       ...        ...  ...         ...        ...          ...   
394  139.000000  3.700000  12.500000  ...           1          1            0   
395  137.528754  4.627244   8.700000  ...           1          1            0   
396  134.000000  2.700000   9.100000  ...           1          1            0   
397  142.000000  5.500000   8.500000  ...           1          1            0   
398  140.000000  5.000000  16.300000  ...           1          1            0   

     ba_present  htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  
0             0        0       0        0          1       1        0  
1             0        0       0        0          1       0        0  
2             0        0       0        0          1       0        0  
3             0        0       0        0          1       0        1  
4             0        0       0        0          1       0        0  
..          ...      ...     ...      ...        ...     ...      ...  
394           0        0       0        0          1       0        0  
395           0        1       1        0          1       0        1  
396           0        1       1        0          0       0        0  
397           0        1       1        0          1       0        1  
398           0        0       0        0          1       0        0  

[399 rows x 27 columns]

In [18]:
dependent=Dataset["classification_yes"]

In [20]:
dependent

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: int32

In [22]:
dependent.value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [24]:
#train and test data
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [25]:
# preproncessing - Standard scaler
from sklearn.preprocessing import StandardScaler
Sc=StandardScaler()
X_train=Sc.fit_transform(X_train)
X_test=Sc.transform(X_test)

In [26]:
X_train

array([[ 0.48681432,  1.79924415, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       [ 0.30305399,  0.26080096, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       [-0.61574769, -0.50842064, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       ...,
       [-0.43198735,  0.26080096, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       [-1.35078903,  0.26080096, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       [-0.06446668, -1.27764223, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456]])

In [27]:
X_test

array([[-0.37073391, -0.50842064, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       [ 0.85433499,  1.03002255,  0.94028379, ..., -1.93649167,
        -0.52223297, -0.44519456],
       [ 1.03809533, -0.50842064, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       ...,
       [-0.24822702,  1.79924415, -0.68384276, ..., -1.93649167,
        -0.52223297, -0.44519456],
       [-0.03431114, -1.27764223,  1.75234707, ...,  0.51639778,
        -0.52223297, -0.44519456],
       [-1.10577525, -1.27764223, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456]])

In [28]:
Y_train

240    1
218    1
101    0
311    1
194    1
      ..
323    1
192    1
117    1
47     0
172    0
Name: classification_yes, Length: 266, dtype: int32

In [34]:
Y_test

132    0
309    1
334    0
196    1
246    1
      ..
349    0
168    0
150    1
392    1
66     0
Name: classification_yes, Length: 133, dtype: int32

In [36]:
# model selection
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV
param_grid={'var_smoothing':np.logspace(0,-9,num=100)}
grid=GridSearchCV(GaussianNB(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,Y_train)


Fitting 5 folds for each of 100 candidates, totalling 500 fits


GridSearchCV(estimator=GaussianNB(), n_jobs=-1,
             param_grid={'var_smoothing': array([1.00000000e+00, 8.11130831e-01, 6.57933225e-01, 5.33669923e-01,
       4.32876128e-01, 3.51119173e-01, 2.84803587e-01, 2.31012970e-01,
       1.87381742e-01, 1.51991108e-01, 1.23284674e-01, 1.00000000e-01,
       8.11130831e-02, 6.57933225e-02, 5.33669923e-02, 4.32876128e-02,
       3.51119173e-02, 2.84803587e-02...
       1.23284674e-07, 1.00000000e-07, 8.11130831e-08, 6.57933225e-08,
       5.33669923e-08, 4.32876128e-08, 3.51119173e-08, 2.84803587e-08,
       2.31012970e-08, 1.87381742e-08, 1.51991108e-08, 1.23284674e-08,
       1.00000000e-08, 8.11130831e-09, 6.57933225e-09, 5.33669923e-09,
       4.32876128e-09, 3.51119173e-09, 2.84803587e-09, 2.31012970e-09,
       1.87381742e-09, 1.51991108e-09, 1.23284674e-09, 1.00000000e-09])},
             scoring='f1_weighted', verbose=3)

In [38]:
re=grid.cv_results_

In [40]:
y_predict=grid.predict(X_test)

In [42]:
grid.predict_proba(X_test)[:,1]

array([6.17770605e-32, 1.00000000e+00, 1.47351445e-24, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.02336567e-21, 6.69268387e-30, 1.00000000e+00, 1.00000000e+00,
       2.17049895e-25, 1.00000000e+00, 2.63311036e-25, 2.92120876e-29,
       1.00000000e+00, 1.69338584e-30, 1.00000000e+00, 1.00000000e+00,
       2.19443427e-23, 1.00000000e+00, 1.00000000e+00, 6.31765026e-24,
       1.00000000e+00, 1.21492073e-28, 2.88675336e-32, 1.01411902e-31,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       2.18200915e-22, 5.38471173e-23, 1.00847887e-31, 9.77545227e-32,
       1.03330877e-20, 9.36004910e-25, 1.00000000e+00, 2.24922661e-24,
       4.83834737e-25, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 4.31602008e-20,
       3.06452531e-02, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 6.48592186e-30, 1.00000000e+00, 1.00000000e+00,
      

In [44]:
# evaluation metrics
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,y_predict)
print("confusion matrix:\n",cm)
from sklearn.metrics import classification_report
clf_rpt=classification_report(Y_test,y_predict)
print("classification report:\n",clf_rpt)
from sklearn.metrics import f1_score
f1_macro=f1_score(Y_test,y_predict)
print("The f1_macro for best parameter{}".format(grid.best_params_),"\n",f1_macro)
from sklearn.metrics import roc_auc_score
roc_score=roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])
print("roc_auc_score:\n",roc_score)




confusion matrix:
 [[51  0]
 [ 3 79]]
classification report:
               precision    recall  f1-score   support

           0       0.94      1.00      0.97        51
           1       1.00      0.96      0.98        82

    accuracy                           0.98       133
   macro avg       0.97      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

The f1_macro for best parameter{'var_smoothing': 0.005336699231206307} 
 0.9813664596273292
roc_auc_score:
 1.0


In [46]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.017206      0.011561         0.010600        0.001162   
1        0.006366      0.000773         0.010274        0.000877   
2        0.005983      0.000973         0.009930        0.001124   
3        0.002646      0.001270         0.007615        0.002493   
4        0.004557      0.001794         0.008815        0.002409   
..            ...           ...              ...             ...   
95       0.002850      0.001239         0.007709        0.004081   
96       0.003557      0.001411         0.007524        0.002687   
97       0.003120      0.000891         0.008310        0.001980   
98       0.003114      0.001013         0.006744        0.002205   
99       0.002825      0.001377         0.008141        0.000808   

    param_var_smoothing                                     params  \
0          1.000000e+00                     {'var_smoothing': 1.0}   
1          8.111308e-01      {'var_smoothing': 0.8111308307896871}   
2          6.579332e-01       {'var_smoothing': 0.657933224657568}   
3          5.336699e-01       {'var_smoothing': 0.533669923120631}   
4          4.328761e-01     {'var_smoothing': 0.43287612810830584}   
..                  ...                                        ...   
95         2.310130e-09   {'var_smoothing': 2.310129700083158e-09}   
96         1.873817e-09   {'var_smoothing': 1.873817422860387e-09}   
97         1.519911e-09   {'var_smoothing': 1.519911082952933e-09}   
98         1.232847e-09  {'var_smoothing': 1.2328467394420635e-09}   
99         1.000000e-09                   {'var_smoothing': 1e-09}   

    split0_test_score  split1_test_score  split2_test_score  \
0            0.740741           0.833495           0.713954   
1            0.740741           0.870619           0.713954   
2            0.760333           0.907402           0.754717   
3            0.779609           0.925764           0.774552   
4            0.798609           0.944161           0.851225   
..                ...                ...                ...   
95           0.981569           0.981014           0.962573   
96           0.981569           0.981014           0.962573   
97           0.981569           0.981014           0.962573   
98           0.981569           0.981014           0.962573   
99           0.981569           0.981014           0.962573   

    split3_test_score  split4_test_score  mean_test_score  std_test_score  \
0            0.851225           0.888515         0.805586        0.066844   
1            0.869925           0.907035         0.820455        0.077662   
2            0.869925           0.925524         0.843580        0.072538   
3            0.888515           0.925524         0.858793        0.068100   
4            0.925524           0.944023         0.892708        0.058195   
..                ...                ...              ...             ...   
95           1.000000           0.981217         0.981275        0.011837   
96           1.000000           0.981217         0.981275        0.011837   
97           1.000000           0.981217         0.981275        0.011837   
98           1.000000           0.981217         0.981275        0.011837   
99           1.000000           0.981217         0.981275        0.011837   

    rank_test_score  
0               100  
1                99  
2                98  
3                97  
4                96  
..              ...  
95               65  
96               65  
97               65  
98               65  
99               65  

[100 rows x 14 columns]

In [48]:
table.to_excel("NaiveBayes_GaussianNB_CKD.xlsx",index=False)

NAIVE BAYES CLASSIFIER_MUTLINOMIALNB

In [49]:
from sklearn.preprocessing import MinMaxScaler
Minmax=MinMaxScaler()
X_train=Minmax.fit_transform(X_train)
X_test=Minmax.transform(X_test)
# MinMaxScaler is used for preprocessing to overcome Value error while running Gridsearch for MultinomialNB
# Value error : Negative values in data passed to MultinomialNB (input X)

In [72]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV
param_grid = {
    'alpha': [0.1, 0.5, 1.0],
    'fit_prior': [True, False]
}
grid=GridSearchCV(MultinomialNB(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,Y_train)


Fitting 5 folds for each of 6 candidates, totalling 30 fits


GridSearchCV(estimator=MultinomialNB(), n_jobs=-1,
             param_grid={'alpha': [0.1, 0.5, 1.0], 'fit_prior': [True, False]},
             scoring='f1_weighted', verbose=3)

In [80]:
re=grid.cv_results_

In [82]:
y_pred=grid.predict(X_test)

In [84]:
# evaluation metrics
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,y_predict)
print("confusion matrix:\n",cm)
from sklearn.metrics import classification_report
clf_rpt=classification_report(Y_test,y_predict)
print("classification report:\n",clf_rpt)
from sklearn.metrics import f1_score
f1_macro=f1_score(Y_test,y_predict)
print("The f1_macro for best parameter{}".format(grid.best_params_),"\n",f1_macro)
from sklearn.metrics import roc_auc_score
roc_score=roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])
print("roc_auc_score:\n",roc_score)

confusion matrix:
 [[51  0]
 [ 2 80]]
classification report:
               precision    recall  f1-score   support

           0       0.96      1.00      0.98        51
           1       1.00      0.98      0.99        82

    accuracy                           0.98       133
   macro avg       0.98      0.99      0.98       133
weighted avg       0.99      0.98      0.99       133

The f1_macro for best parameter{'alpha': 0.1, 'fit_prior': True} 
 0.9876543209876543
roc_auc_score:
 1.0


In [86]:
table=pd.DataFrame.from_dict(re)

In [88]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_alpha  \
0       0.044113      0.021232         0.008498        0.002391          0.1   
1       0.053242      0.001986         0.008389        0.001959          0.1   
2       0.020956      0.022687         0.005888        0.002657          0.5   
3       0.006698      0.000804         0.008711        0.002324          0.5   
4       0.005928      0.000898         0.008065        0.001805          1.0   
5       0.006030      0.000750         0.009200        0.000164          1.0   

   param_fit_prior                              params  split0_test_score  \
0             True   {'alpha': 0.1, 'fit_prior': True}           0.981569   
1            False  {'alpha': 0.1, 'fit_prior': False}           0.981569   
2             True   {'alpha': 0.5, 'fit_prior': True}           0.981569   
3            False  {'alpha': 0.5, 'fit_prior': False}           0.981569   
4             True   {'alpha': 1.0, 'fit_prior': True}           0.981569   
5            False  {'alpha': 1.0, 'fit_prior': False}           0.981569   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.962264           0.962573           0.981217           0.981217   
1           0.962264           0.962573           0.981217           0.981217   
2           0.962264           0.962573           0.981217           0.981217   
3           0.962264           0.962573           0.981217           0.981217   
4           0.962264           0.962573           0.981217           0.981217   
5           0.962264           0.962573           0.962573           0.981217   

   mean_test_score  std_test_score  rank_test_score  
0         0.973768        0.009268                1  
1         0.973768        0.009268                1  
2         0.973768        0.009268                1  
3         0.973768        0.009268                1  
4         0.973768        0.009268                1  
5         0.970039        0.009272                6

In [90]:
table.to_excel("MultinomialNBClassifier_CKD.xlsx",index=False)

NAIVE BAYES CLASSIFIER_BERNOULLINB

In [92]:
from sklearn.naive_bayes import BernoulliNB

param_grid = {
    'alpha': [0.1, 0.5, 1.0],
    'binarize': [0.0, 0.5, 1.0],
    'fit_prior': [True, False]
}
grid=GridSearchCV(BernoulliNB(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
# fitting the model
grid.fit(X_train,Y_train)



Fitting 5 folds for each of 18 candidates, totalling 90 fits


GridSearchCV(estimator=BernoulliNB(), n_jobs=-1,
             param_grid={'alpha': [0.1, 0.5, 1.0], 'binarize': [0.0, 0.5, 1.0],
                         'fit_prior': [True, False]},
             scoring='f1_weighted', verbose=3)

In [94]:
re=grid.cv_results_

In [96]:
y_pred=grid.predict(X_test)

In [98]:
# evaluation metrics
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,y_predict)
print("confusion matrix:\n",cm)
from sklearn.metrics import classification_report
clf_rpt=classification_report(Y_test,y_predict)
print("classification report:\n",clf_rpt)
from sklearn.metrics import f1_score
f1_macro=f1_score(Y_test,y_predict)
print("The f1_macro for best parameter{}".format(grid.best_params_),"\n",f1_macro)
from sklearn.metrics import roc_auc_score
roc_score=roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])
print("roc_auc_score:\n",roc_score)

confusion matrix:
 [[51  0]
 [ 2 80]]
classification report:
               precision    recall  f1-score   support

           0       0.96      1.00      0.98        51
           1       1.00      0.98      0.99        82

    accuracy                           0.98       133
   macro avg       0.98      0.99      0.98       133
weighted avg       0.99      0.98      0.99       133

The f1_macro for best parameter{'alpha': 0.1, 'binarize': 0.0, 'fit_prior': True} 
 0.9876543209876543
roc_auc_score:
 0.9966523194643712


In [100]:
table=pd.DataFrame.from_dict(re)

In [102]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_alpha  \
0        0.004303      0.001621         0.007620        0.002829          0.1   
1        0.004581      0.000620         0.007417        0.001193          0.1   
2        0.004717      0.001135         0.007131        0.000985          0.1   
3        0.005516      0.000858         0.009879        0.002740          0.1   
4        0.004223      0.001877         0.006413        0.002055          0.1   
5        0.006486      0.001411         0.008728        0.001528          0.1   
6        0.005908      0.001729         0.012379        0.002100          0.5   
7        0.007423      0.000891         0.009033        0.002914          0.5   
8        0.006648      0.002648         0.010288        0.001243          0.5   
9        0.006995      0.001598         0.011660        0.001625          0.5   
10       0.007936      0.001741         0.008818        0.001292          0.5   
11       0.006188      0.001438         0.009855        0.001148          0.5   
12       0.007228      0.001359         0.010069        0.001376          1.0   
13       0.005192      0.000981         0.008135        0.003038          1.0   
14       0.006700      0.000828         0.008894        0.001160          1.0   
15       0.005717      0.001572         0.008591        0.001888          1.0   
16       0.004932      0.002206         0.008132        0.001269          1.0   
17       0.005150      0.001474         0.007515        0.000388          1.0   

    param_binarize  param_fit_prior  \
0              0.0             True   
1              0.0            False   
2              0.5             True   
3              0.5            False   
4              1.0             True   
5              1.0            False   
6              0.0             True   
7              0.0            False   
8              0.5             True   
9              0.5            False   
10             1.0             True   
11             1.0            False   
12             0.0             True   
13             0.0            False   
14             0.5             True   
15             0.5            False   
16             1.0             True   
17             1.0            False   

                                               params  split0_test_score  \
0   {'alpha': 0.1, 'binarize': 0.0, 'fit_prior': T...           0.981569   
1   {'alpha': 0.1, 'binarize': 0.0, 'fit_prior': F...           0.981569   
2   {'alpha': 0.1, 'binarize': 0.5, 'fit_prior': T...           0.981569   
3   {'alpha': 0.1, 'binarize': 0.5, 'fit_prior': F...           0.963284   
4   {'alpha': 0.1, 'binarize': 1.0, 'fit_prior': T...           0.486532   
5   {'alpha': 0.1, 'binarize': 1.0, 'fit_prior': F...           0.486532   
6   {'alpha': 0.5, 'binarize': 0.0, 'fit_prior': T...           0.926978   
7   {'alpha': 0.5, 'binarize': 0.0, 'fit_prior': F...           0.926978   
8   {'alpha': 0.5, 'binarize': 0.5, 'fit_prior': T...           0.908877   
9   {'alpha': 0.5, 'binarize': 0.5, 'fit_prior': F...           0.908877   
10  {'alpha': 0.5, 'binarize': 1.0, 'fit_prior': T...           0.486532   
11  {'alpha': 0.5, 'binarize': 1.0, 'fit_prior': F...           0.486532   
12  {'alpha': 1.0, 'binarize': 0.0, 'fit_prior': T...           0.926978   
13  {'alpha': 1.0, 'binarize': 0.0, 'fit_prior': F...           0.926978   
14  {'alpha': 1.0, 'binarize': 0.5, 'fit_prior': T...           0.908877   
15  {'alpha': 1.0, 'binarize': 0.5, 'fit_prior': F...           0.890759   
16  {'alpha': 1.0, 'binarize': 1.0, 'fit_prior': T...           0.486532   
17  {'alpha': 1.0, 'binarize': 1.0, 'fit_prior': F...           0.486532   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.981014           0.962573           1.000000   
1            0.981014           0.962573           1.000000   
2            0.962264           0.925524           1.000000   
3            0.962264    

In [104]:
table.to_excel("BernoulliNBClassifier_CKD.xlsx",index=False)

NAIVE BAYES_COMPLEMENTNB

In [66]:
from sklearn.naive_bayes import ComplementNB
param_grid = {
    'alpha': [0.1, 0.5, 1.0, 2.0],
    'norm': [True, False]
}
grid=GridSearchCV(ComplementNB(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
# fitting the mode
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits


GridSearchCV(estimator=ComplementNB(), n_jobs=-1,
             param_grid={'alpha': [0.1, 0.5, 1.0, 2.0], 'norm': [True, False]},
             scoring='f1_weighted', verbose=3)

In [68]:
y_predict=grid.predict(X_test)

In [106]:
re=grid.cv_results_

In [70]:
# evaluation metrics
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,y_predict)
print("confusion matrix:\n",cm)
from sklearn.metrics import classification_report
clf_rpt=classification_report(Y_test,y_predict)
print("classification report:\n",clf_rpt)
from sklearn.metrics import f1_score
f1_macro=f1_score(Y_test,y_predict)
print("The f1_macro for best parameter{}".format(grid.best_params_),"\n",f1_macro)
from sklearn.metrics import roc_auc_score
roc_score=roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])
print("roc_auc_score:\n",roc_score)


confusion matrix:
 [[51  0]
 [ 2 80]]
classification report:
               precision    recall  f1-score   support

           0       0.96      1.00      0.98        51
           1       1.00      0.98      0.99        82

    accuracy                           0.98       133
   macro avg       0.98      0.99      0.98       133
weighted avg       0.99      0.98      0.99       133

The f1_macro for best parameter{'alpha': 0.1, 'norm': False} 
 0.9876543209876543
roc_auc_score:
 1.0


In [108]:
table=pd.DataFrame.from_dict(re)

In [110]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_alpha  \
0        0.004303      0.001621         0.007620        0.002829          0.1   
1        0.004581      0.000620         0.007417        0.001193          0.1   
2        0.004717      0.001135         0.007131        0.000985          0.1   
3        0.005516      0.000858         0.009879        0.002740          0.1   
4        0.004223      0.001877         0.006413        0.002055          0.1   
5        0.006486      0.001411         0.008728        0.001528          0.1   
6        0.005908      0.001729         0.012379        0.002100          0.5   
7        0.007423      0.000891         0.009033        0.002914          0.5   
8        0.006648      0.002648         0.010288        0.001243          0.5   
9        0.006995      0.001598         0.011660        0.001625          0.5   
10       0.007936      0.001741         0.008818        0.001292          0.5   
11       0.006188      0.001438         0.009855        0.001148          0.5   
12       0.007228      0.001359         0.010069        0.001376          1.0   
13       0.005192      0.000981         0.008135        0.003038          1.0   
14       0.006700      0.000828         0.008894        0.001160          1.0   
15       0.005717      0.001572         0.008591        0.001888          1.0   
16       0.004932      0.002206         0.008132        0.001269          1.0   
17       0.005150      0.001474         0.007515        0.000388          1.0   

    param_binarize  param_fit_prior  \
0              0.0             True   
1              0.0            False   
2              0.5             True   
3              0.5            False   
4              1.0             True   
5              1.0            False   
6              0.0             True   
7              0.0            False   
8              0.5             True   
9              0.5            False   
10             1.0             True   
11             1.0            False   
12             0.0             True   
13             0.0            False   
14             0.5             True   
15             0.5            False   
16             1.0             True   
17             1.0            False   

                                               params  split0_test_score  \
0   {'alpha': 0.1, 'binarize': 0.0, 'fit_prior': T...           0.981569   
1   {'alpha': 0.1, 'binarize': 0.0, 'fit_prior': F...           0.981569   
2   {'alpha': 0.1, 'binarize': 0.5, 'fit_prior': T...           0.981569   
3   {'alpha': 0.1, 'binarize': 0.5, 'fit_prior': F...           0.963284   
4   {'alpha': 0.1, 'binarize': 1.0, 'fit_prior': T...           0.486532   
5   {'alpha': 0.1, 'binarize': 1.0, 'fit_prior': F...           0.486532   
6   {'alpha': 0.5, 'binarize': 0.0, 'fit_prior': T...           0.926978   
7   {'alpha': 0.5, 'binarize': 0.0, 'fit_prior': F...           0.926978   
8   {'alpha': 0.5, 'binarize': 0.5, 'fit_prior': T...           0.908877   
9   {'alpha': 0.5, 'binarize': 0.5, 'fit_prior': F...           0.908877   
10  {'alpha': 0.5, 'binarize': 1.0, 'fit_prior': T...           0.486532   
11  {'alpha': 0.5, 'binarize': 1.0, 'fit_prior': F...           0.486532   
12  {'alpha': 1.0, 'binarize': 0.0, 'fit_prior': T...           0.926978   
13  {'alpha': 1.0, 'binarize': 0.0, 'fit_prior': F...           0.926978   
14  {'alpha': 1.0, 'binarize': 0.5, 'fit_prior': T...           0.908877   
15  {'alpha': 1.0, 'binarize': 0.5, 'fit_prior': F...           0.890759   
16  {'alpha': 1.0, 'binarize': 1.0, 'fit_prior': T...           0.486532   
17  {'alpha': 1.0, 'binarize': 1.0, 'fit_prior': F...           0.486532   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.981014           0.962573           1.000000   
1            0.981014           0.962573           1.000000   
2            0.962264           0.925524           1.000000   
3            0.962264    

In [112]:
table.to_excel("ComplementNBClassifier_CKD.xlsx",index=False)

NAIVE BAYES_CATEGORICALNB

In [130]:
from sklearn.naive_bayes import CategoricalNB
param_grid = {
    'alpha': [0.1, 0.5, 1.0],
    'fit_prior': [True, False],
    'min_categories':[10]
}
grid=GridSearchCV(CategoricalNB(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
#fitting the model
grid.fit(X_train,Y_train)
# here min_categrories is mentioned 10 to overcome Index error while predicting the output for X_test

Fitting 5 folds for each of 6 candidates, totalling 30 fits


GridSearchCV(estimator=CategoricalNB(), n_jobs=-1,
             param_grid={'alpha': [0.1, 0.5, 1.0], 'fit_prior': [True, False],
                         'min_categories': [10]},
             scoring='f1_weighted', verbose=3)

In [128]:
y_predict=grid.predict(X_test)

In [132]:
re=grid.cv_results_

In [134]:
# evaluation metrics
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,y_predict)
print("confusion matrix:\n",cm)
from sklearn.metrics import classification_report
clf_rpt=classification_report(Y_test,y_predict)
print("classification report:\n",clf_rpt)
from sklearn.metrics import f1_score
f1_macro=f1_score(Y_test,y_predict)
print("The f1_macro for best parameter{}".format(grid.best_params_),"\n",f1_macro)
from sklearn.metrics import roc_auc_score
roc_score=roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])
print("roc_auc_score:\n",roc_score)

confusion matrix:
 [[51  0]
 [ 4 78]]
classification report:
               precision    recall  f1-score   support

           0       0.93      1.00      0.96        51
           1       1.00      0.95      0.97        82

    accuracy                           0.97       133
   macro avg       0.96      0.98      0.97       133
weighted avg       0.97      0.97      0.97       133

The f1_macro for best parameter{'alpha': 0.1, 'fit_prior': True, 'min_categories': 10} 
 0.975
roc_auc_score:
 0.9903156384505022


In [140]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_alpha  \
0       0.013686      0.005288         0.008222        0.002989          0.1   
1       0.016773      0.004731         0.008799        0.002535          0.1   
2       0.012933      0.004984         0.006973        0.002929          0.5   
3       0.017631      0.005482         0.011197        0.001224          0.5   
4       0.016353      0.002217         0.010779        0.000973          1.0   
5       0.014582      0.005459         0.009044        0.001342          1.0   

   param_fit_prior  param_min_categories  \
0             True                    10   
1            False                    10   
2             True                    10   
3            False                    10   
4             True                    10   
5            False                    10   

                                              params  split0_test_score  \
0  {'alpha': 0.1, 'fit_prior': True, 'min_categor...           0.981569   
1  {'alpha': 0.1, 'fit_prior': False, 'min_catego...           0.981569   
2  {'alpha': 0.5, 'fit_prior': True, 'min_categor...           0.981569   
3  {'alpha': 0.5, 'fit_prior': False, 'min_catego...           0.981569   
4  {'alpha': 1.0, 'fit_prior': True, 'min_categor...           0.981569   
5  {'alpha': 1.0, 'fit_prior': False, 'min_catego...           0.981569   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.962264           0.962573           0.981217           0.981217   
1           0.962264           0.962573           0.981217           0.981217   
2           0.962264           0.962573           0.981217           0.981217   
3           0.962264           0.962573           0.981217           0.981217   
4           0.962264           0.962573           0.981217           0.981217   
5           0.962264           0.962573           0.981217           0.981217   

   mean_test_score  std_test_score  rank_test_score  
0         0.973768        0.009268                1  
1         0.973768        0.009268                1  
2         0.973768        0.009268                1  
3         0.973768        0.009268                1  
4         0.973768        0.009268                1  
5         0.973768        0.009268                1

In [142]:
table.to_excel("CategoricalNBClassifier_CKD.xlsx",index=False)